services:
  proxy:
    image: envoyproxy/envoy@sha256:b21240e552b588017072424716c0bce30000f49deed6262bde55b042b5acfd97
    command: ["envoy", "-c", "/etc/envoy/envoy.yaml", "--concurrency", "2", "--log-level", "warning"]
    ports: ["127.0.0.1:18082:18082"]
    extra_hosts: ["host.docker.internal:host-gateway"]
    volumes: ["./inspection/envoy-inline.yaml:/etc/envoy/envoy.yaml:ro"]
